---
language: php

addons:
  apt:
    packages:
    - elinks # For dysplaying php files on console.
    # - empty-expect

cache:
  directories:
  - $HOME/.composer/cache/files

php:
- nightly
- 7.2 # For Drupal 8.5+
- 7.1 # Recommanded for Drupal 8.4
# - 7.0 # Debian 9
- 5.6 # Minimum for Drush 9, Debian 8
# - 5.5 # Minimum for Drupal 8

# addons:
  # mariadb: # '10.0' # Do not know about other versions...
  # postgresql: # "9.6" # Most recent with trusty is 9.6

services:
- mysql
- postgresql

env:
  global:
  - DRUPAL_DEV_VERSION="^8.5@alpha"
  - PATH=~/.composer/vendor/bin:$PATH
  matrix:
  - LANGCODE="en" PROFILE="minimal" DB_TYPE="mysql" DB_HOST="localhost"
  - LANGCODE="en" PROFILE="minimal" DB_TYPE="sqlite"
  - LANGCODE="en" PROFILE="minimal" DB_TYPE="pgsql" DB_HOST="/var/run/postgresql" DB_PORT=5432
  - LANGCODE="fr" PROFILE="minimal" DB_TYPE="mysql" DB_HOST="localhost"
  - LANGCODE="fr" PROFILE="minimal" DB_TYPE="sqlite"
  - LANGCODE="fr" PROFILE="minimal" DB_TYPE="pgsql" DB_HOST="/var/run/postgresql" DB_PORT=5432
  - LANGCODE="en" PROFILE="standard" DB_TYPE="mysql" DB_HOST="localhost"
  - LANGCODE="en" PROFILE="standard" DB_TYPE="sqlite"
  - LANGCODE="en" PROFILE="standard" DB_TYPE="pgsql" DB_HOST="/var/run/postgresql" DB_PORT=5432
  - LANGCODE="fr" PROFILE="standard" DB_TYPE="mysql" DB_HOST="localhost"
  - LANGCODE="fr" PROFILE="standard" DB_TYPE="sqlite"
  - LANGCODE="fr" PROFILE="standard" DB_TYPE="pgsql" DB_HOST="/var/run/postgresql" DB_PORT=5432

matrix:
  fast_finish: true
  include:
  - php: 7.2
    env: LANGCODE="en" PROFILE="minimal" DRUPAL_VERSION=$DRUPAL_DEV_VERSION DB_TYPE="mysql" DB_HOST="localhost"
  - php: 7.2
    env: LANGCODE="en" PROFILE="minimal" DRUPAL_VERSION="^8.5@alpha" DB_TYPE="sqlite"
  - php: 7.2
    env: LANGCODE="en" PROFILE="minimal" DRUPAL_VERSION="^8.5@alpha" DB_TYPE="pgsql" DB_HOST="/var/run/postgresql" DB_PORT=5432
  - php: 7.2
    env: LANGCODE="fr" PROFILE="minimal" DRUPAL_VERSION="^8.5@alpha" DB_TYPE="mysql" DB_HOST="localhost"
  - php: 7.2
    env: LANGCODE="fr" PROFILE="minimal" DRUPAL_VERSION="^8.5@alpha" DB_TYPE="sqlite"
  - php: 7.2
    env: LANGCODE="fr" PROFILE="minimal" DRUPAL_VERSION="^8.5@alpha" DB_TYPE="pgsql" DB_HOST="/var/run/postgresql" DB_PORT=5432
  - php: 7.2
    env: LANGCODE="en" PROFILE="standard" DRUPAL_VERSION="^8.5@alpha" DB_TYPE="mysql" DB_HOST="localhost"
  - php: 7.2
    env: LANGCODE="en" PROFILE="standard" DRUPAL_VERSION="^8.5@alpha" DB_TYPE="sqlite"
  - php: 7.2
    env: LANGCODE="en" PROFILE="standard" DRUPAL_VERSION="^8.5@alpha" DB_TYPE="pgsql" DB_HOST="/var/run/postgresql" DB_PORT=5432
  - php: 7.2
    env: LANGCODE="fr" PROFILE="standard" DRUPAL_VERSION="^8.5@alpha" DB_TYPE="mysql" DB_HOST="localhost"
  - php: 7.2
    env: LANGCODE="fr" PROFILE="standard" DRUPAL_VERSION="^8.5@alpha" DB_TYPE="sqlite"
  - php: 7.2
    env: LANGCODE="fr" PROFILE="standard" DRUPAL_VERSION="^8.5@alpha" DB_TYPE="pgsql" DB_HOST="/var/run/postgresql" DB_PORT=5432
  - php: 5.6
    env: LANGCODE="en" PROFILE="minimal" DRUPAL_VERSION="^8.5@alpha" DB_TYPE="mysql" DB_HOST="localhost"
  - php: 5.6
    env: LANGCODE="en" PROFILE="minimal" DRUPAL_VERSION="^8.5@alpha" DB_TYPE="sqlite"
  - php: 5.6
    env: LANGCODE="en" PROFILE="minimal" DRUPAL_VERSION="^8.5@alpha" DB_TYPE="pgsql" DB_HOST="/var/run/postgresql" DB_PORT=5432
  - php: 5.6
    env: LANGCODE="fr" PROFILE="minimal" DRUPAL_VERSION="^8.5@alpha" DB_TYPE="mysql" DB_HOST="localhost"
  - php: 5.6
    env: LANGCODE="fr" PROFILE="minimal" DRUPAL_VERSION="^8.5@alpha" DB_TYPE="sqlite"
  - php: 5.6
    env: LANGCODE="fr" PROFILE="minimal" DRUPAL_VERSION="^8.5@alpha" DB_TYPE="pgsql" DB_HOST="/var/run/postgresql" DB_PORT=5432
  - php: 5.6
    env: LANGCODE="en" PROFILE="standard" DRUPAL_VERSION="^8.5@alpha" DB_TYPE="mysql" DB_HOST="localhost"
  - php: 5.6
    env: LANGCODE="en" PROFILE="standard" DRUPAL_VERSION="^8.5@alpha" DB_TYPE="sqlite"
  - php: 5.6
    env: LANGCODE="en" PROFILE="standard" DRUPAL_VERSION="^8.5@alpha" DB_TYPE="pgsql" DB_HOST="/var/run/postgresql" DB_PORT=5432
  - php: 5.6
    env: LANGCODE="fr" PROFILE="standard" DRUPAL_VERSION="^8.5@alpha" DB_TYPE="mysql" DB_HOST="localhost"
  - php: 5.6
    env: LANGCODE="fr" PROFILE="standard" DRUPAL_VERSION="^8.5@alpha" DB_TYPE="sqlite"
  - php: 5.6
    env: LANGCODE="fr" PROFILE="standard" DRUPAL_VERSION="^8.5@alpha" DB_TYPE="pgsql" DB_HOST="/var/run/postgresql" DB_PORT=5432
  allow_failures:
  # - php: 7.0 # sensiolabs/security-checker 4.1.7
  - php: 7.3
  - php: nightly
  - env: LANGCODE="en" PROFILE="minimal" DRUPAL_VERSION="^8.5@alpha" DB_TYPE="mysql" DB_HOST="localhost"
  - env: LANGCODE="en" PROFILE="minimal" DRUPAL_VERSION="^8.5@alpha" DB_TYPE="sqlite"
  - env: LANGCODE="en" PROFILE="minimal" DRUPAL_VERSION="^8.5@alpha" DB_TYPE="pgsql" DB_HOST="/var/run/postgresql" DB_PORT=5432
  - env: LANGCODE="fr" PROFILE="minimal" DRUPAL_VERSION="^8.5@alpha" DB_TYPE="mysql" DB_HOST="localhost"
  - env: LANGCODE="fr" PROFILE="minimal" DRUPAL_VERSION="^8.5@alpha" DB_TYPE="sqlite"
  - env: LANGCODE="fr" PROFILE="minimal" DRUPAL_VERSION="^8.5@alpha" DB_TYPE="pgsql" DB_HOST="/var/run/postgresql" DB_PORT=5432
  - env: LANGCODE="en" PROFILE="standard" DRUPAL_VERSION="^8.5@alpha" DB_TYPE="mysql" DB_HOST="localhost"
  - env: LANGCODE="en" PROFILE="standard" DRUPAL_VERSION="^8.5@alpha" DB_TYPE="sqlite"
  - env: LANGCODE="en" PROFILE="standard" DRUPAL_VERSION="^8.5@alpha" DB_TYPE="pgsql" DB_HOST="/var/run/postgresql" DB_PORT=5432
  - env: LANGCODE="fr" PROFILE="standard" DRUPAL_VERSION="^8.5@alpha" DB_TYPE="mysql" DB_HOST="localhost"
  - env: LANGCODE="fr" PROFILE="standard" DRUPAL_VERSION="^8.5@alpha" DB_TYPE="sqlite"
  - env: LANGCODE="fr" PROFILE="standard" DRUPAL_VERSION="^8.5@alpha" DB_TYPE="pgsql" DB_HOST="/var/run/postgresql" DB_PORT=5432

before_install:
# - install --directory .travis/bin
# - if [[ -f config/parameters.yml.travis ]]; then cp config/parameters.yml.travis config/parameters.yml; fi
# - if [[ "7.0" < $TRAVIS_PHP_VERSION ]]; then
#     wget http://get.sensiolabs.org/security-checker.phar --output-document=.travis/bin/security-checker;
#   fi
- composer global require --dev sensiolabs/security-checker

# - pip install pygments # but now pygmentize is no more used right here.
- go get -u github.com/jingweno/ccat

install:
- composer create-project --no-install --stability dev --no-interaction drupal-composer/drupal-project my-project $SKELETON_VERSION
- ls --color
- cd my-project
- if [[ -v DRUPAL_VERSION ]]; then
    composer -vv require --no-update drupal/core:$DRUPAL_VERSION;
  fi
- composer install

before_script:
- composer show --latest
- composer show --tree
- composer why --tree phpunit/phpunit
- composer why --tree symfony-cmf/routing
- composer why --tree symfony/http-kernel
# - bin/console
- ls --color
- ls drush
- ls --color vendor/bin
- $GOPATH/bin/ccat composer.json
- find . -name profiles
# - cd web
- ls --color
# - ls --color web/profiles
# - ls --color web/core/profiles
- vendor/bin/drupal
- vendor/bin/drupal help init # Copy configuration files.
- vendor/bin/drupal help chain --file=~/.console/chain/quick-start.yml # Used to eg. download, install and serve.
- vendor/bin/drupal help quick:start # Maybe shortcut for chain --file=~/.console/chain/quick-start.yml
- vendor/bin/drupal help site:new # Download.
- vendor/bin/drupal help check
- vendor/bin/drupal help site:install # Maybe installation: basic configuration
- vendor/bin/drupal help server
- vendor/bin/drush 2> /dev/null # drush/drush 8.1.15 does not fold and has lots of warnings (may be with too recent php version).
- vendor/bin/drush help runserver
- vendor/bin/drupal check
# - mysql -e "CREATE DATABASE IF NOT EXISTS $USER;"
- psql --command="\l" -U postgres
- psql --command="create database $USER;" -U postgres # --encoding=UTF8 --owner=$USER
- psql --command="\l" -U postgres
- vendor/bin/drupal site:install $PROFILE --yes --no-interaction --verbose
  --langcode=$LANGCODE
  --db-type=$DB_TYPE
  --db-host=$DB_HOST
  --db-port=$DB_PORT
  --db-name=$USER
  --db-user=$USER
  --db-pass=""
  --site-name="Project Only"
  --site-mail="admin@example.com"
  --account-name="admin"
  --account-mail="admin@example.com"
  --account-pass="admin"

- vendor/bin/drush core:status
- vendor/bin/drush core:requirements
- vendor/bin/drush
- vendor/bin/drush help pm:enable
- vendor/bin/drush help theme:enable


- composer require drupal/admin_toolbar
- vendor/bin/drush pm:enable --yes admin_toolbar # The following module(s) will be enabled: admin_toolbar, toolbar, breakpoint

- composer require drupal/token
- vendor/bin/drush pm:enable token

- composer require drupal/pathauto
- vendor/bin/drush pm:enable --yes pathauto # The following module(s) will be enabled: pathauto, ctools, path

- composer require drupal/metatag #?
- vendor/bin/drush pm:enable metatag

- composer require drupal/entity_reference_revisions #?
- vendor/bin/drush pm:enable entity_reference_revisions

- composer require drupal/paragraphs #?
- vendor/bin/drush pm:enable paragraphs

- composer require drupal/field_group #?
- vendor/bin/drush pm:enable field_group

- composer require drupal/devel #?
- vendor/bin/drush pm:enable devel

- composer require drupal/webform
- vendor/bin/drush pm:enable --yes webform # The following module(s) will be enabled: webform, contribute

- composer require drupal/video_embed_field
- vendor/bin/drush pm:enable -y video_embed_wysiwyg
# video_embed_field: The following module(s) will be enabled: video_embed_field, image

- composer require drupal/video_embed_facebook
- vendor/bin/drush pm:enable -y video_embed_facebook

- composer require drupal/video_embed_dailymotion
- vendor/bin/drush pm:enable -y video_embed_dailymotion

- composer require drupal/video_embed_instagram
- vendor/bin/drush pm:enable -y video_embed_instagram

- composer require drupal/video_embed_ted
- vendor/bin/drush pm:enable -y video_embed_ted

- composer require drupal/video_embed_html5
- vendor/bin/drush pm:enable -y video_embed_html5

- composer require drupal/redirect
- vendor/bin/drush pm:enable --yes redirect # The following module(s) will be enabled: redirect, link, views

- composer require drupal/entity_browser # Is it really needed?
- vendor/bin/drush pm:enable entity_browser

- composer require drupal/pixture_reloaded
- vendor/bin/drush theme:enable -y pixture_reloaded
- vendor/bin/drush config-set --yes system.theme default pixture_reloaded

# - composer require drupal/media_entity_browser # Is it really needed?
# - drush pm-enable --yes media_entity_browser
# The following module(s) will be enabled: media_entity_browser, media_entity, entity
# Error: Call to a member function getConfigDependencyKey() on null in /home/travis/build/drupal-composer-drupal-project-demo/project-only/my-project/web/modules/contrib/entity_browser/src/Plugin/EntityBrowser/Widget/View.php on line 277
#  Installing drupal/entity (1.0.0-beta1): Downloading (100%)
#  Installing drupal/media_entity (1.7.0): Downloading (100%)
#  Installing drupal/media_entity_browser (1.0.0-beta3): Downloading (100%)

- composer global show --latest
- composer --working-dir=.. show --latest
- composer --working-dir=.. show --tree
- vendor/bin/drush pm:list
# - ../vendor/bin/drush pm-projectinfo # The pm-projectinfo command was deprecated. Please see `drush pm:list` and `composer show`
- vendor/bin/drupal server --yes --no-interaction --learning & printf 'HEAD / HTTP/1.1\r\n\r\n' | socat - TCP4:localhost:8088,forever # Waiting for server to connect.

script:
- elinks http://localhost:8088/ -dump-color-mode 4 -dump
- elinks http://localhost:8088/core/install.php?langcode=en -dump-color-mode 4 -dump

# - cd ..
- security-checker security:check --end-point=http://security.sensiolabs.org/check_lock
- security-checker security:check --end-point=http://security.sensiolabs.org/check_lock ~/.composer/composer.lock
- 'curl -H "Accept: text/plain" https://security.sensiolabs.org/check_lock -F lock=@composer.lock'
  #^ This checks that the application doesn't use dependencies with known security vulnerabilities
