---
language: php
addons:
  apt:
    packages:
    - elinks # For dysplaying php files on console.
    - empty-expect

cache:
  directories:
    - $HOME/.composer/cache/files

php: # symfony/skeleton requires ^7.0.8
- 5.6
- 7.0 # SYMFONY_VERSION="^3.4" only one version of skeleton working with php 7.0
- 7.1 # Recommanded for Drupal 8.4
- 7.2 # for Drupal 8.5+
- nightly

# addons:
  # mariadb: # '10.0' # Do not know about other versions...
  # postgresql: # "9.6" # Most recent with trusty is 9.6

services:
- mysql
- postgresql

env:
  global:
  matrix:
  - LANGCODE="en" PROFILE="minimal" DB_TYPE="mysql" DB_HOST="localhost"
  - LANGCODE="en" PROFILE="minimal" DB_TYPE="sqlite"
  - LANGCODE="en" PROFILE="minimal" DB_TYPE="pgsql" DB_HOST="/var/run/postgresql" DB_PORT=5432
  - LANGCODE="fr" PROFILE="minimal" DB_TYPE="mysql" DB_HOST="localhost"
  - LANGCODE="fr" PROFILE="minimal" DB_TYPE="sqlite"
  - LANGCODE="fr" PROFILE="minimal" DB_TYPE="pgsql" DB_HOST="/var/run/postgresql" DB_PORT=5432
  - LANGCODE="en" PROFILE="standard" DB_TYPE="mysql" DB_HOST="localhost"
  - LANGCODE="en" PROFILE="standard" DB_TYPE="sqlite"
  - LANGCODE="en" PROFILE="standard" DB_TYPE="pgsql" DB_HOST="/var/run/postgresql" DB_PORT=5432
  - LANGCODE="fr" PROFILE="standard" DB_TYPE="mysql" DB_HOST="localhost"
  - LANGCODE="fr" PROFILE="standard" DB_TYPE="sqlite"
  - LANGCODE="fr" PROFILE="standard" DB_TYPE="pgsql" DB_HOST="/var/run/postgresql" DB_PORT=5432

matrix:
  fast_finish: true
  include:
  - php: 7.2
    env: LANGCODE="en" PROFILE="minimal" DRUPAL_VERSION="^8.5@alpha" DB_TYPE="mysql" DB_HOST="localhost"
  - php: 7.2
    env: LANGCODE="en" PROFILE="minimal" DRUPAL_VERSION="^8.5@alpha" DB_TYPE="sqlite"
  - php: 7.2
    env: LANGCODE="en" PROFILE="minimal" DRUPAL_VERSION="^8.5@alpha" DB_TYPE="pgsql" DB_HOST="/var/run/postgresql" DB_PORT=5432
  - php: 7.2
    env: LANGCODE="fr" PROFILE="minimal" DRUPAL_VERSION="^8.5@alpha" DB_TYPE="mysql" DB_HOST="localhost"
  - php: 7.2
    env: LANGCODE="fr" PROFILE="minimal" DRUPAL_VERSION="^8.5@alpha" DB_TYPE="sqlite"
  - php: 7.2
    env: LANGCODE="fr" PROFILE="minimal" DRUPAL_VERSION="^8.5@alpha" DB_TYPE="pgsql" DB_HOST="/var/run/postgresql" DB_PORT=5432
  - php: 7.2
    env: LANGCODE="en" PROFILE="standard" DRUPAL_VERSION="^8.5@alpha" DB_TYPE="mysql" DB_HOST="localhost"
  - php: 7.2
    env: LANGCODE="en" PROFILE="standard" DRUPAL_VERSION="^8.5@alpha" DB_TYPE="sqlite"
  - php: 7.2
    env: LANGCODE="en" PROFILE="standard" DRUPAL_VERSION="^8.5@alpha" DB_TYPE="pgsql" DB_HOST="/var/run/postgresql" DB_PORT=5432
  - php: 7.2
    env: LANGCODE="fr" PROFILE="standard" DRUPAL_VERSION="^8.5@alpha" DB_TYPE="mysql" DB_HOST="localhost"
  - php: 7.2
    env: LANGCODE="fr" PROFILE="standard" DRUPAL_VERSION="^8.5@alpha" DB_TYPE="sqlite"
  - php: 7.2
    env: LANGCODE="fr" PROFILE="standard" DRUPAL_VERSION="^8.5@alpha" DB_TYPE="pgsql" DB_HOST="/var/run/postgresql" DB_PORT=5432
  allow_failures:
  - php: 7.0 # sensiolabs/security-checker 4.1.7
  - php: 7.3
  - php: nightly
  - env: LANGCODE="en" PROFILE="minimal" DRUPAL_VERSION="^8.5@alpha" DB_TYPE="mysql" DB_HOST="localhost"
  - env: LANGCODE="en" PROFILE="minimal" DRUPAL_VERSION="^8.5@alpha" DB_TYPE="sqlite"
  - env: LANGCODE="en" PROFILE="minimal" DRUPAL_VERSION="^8.5@alpha" DB_TYPE="pgsql" DB_HOST="/var/run/postgresql" DB_PORT=5432
  - env: LANGCODE="fr" PROFILE="minimal" DRUPAL_VERSION="^8.5@alpha" DB_TYPE="mysql" DB_HOST="localhost"
  - env: LANGCODE="fr" PROFILE="minimal" DRUPAL_VERSION="^8.5@alpha" DB_TYPE="sqlite"
  - env: LANGCODE="fr" PROFILE="minimal" DRUPAL_VERSION="^8.5@alpha" DB_TYPE="pgsql" DB_HOST="/var/run/postgresql" DB_PORT=5432
  - env: LANGCODE="en" PROFILE="standard" DRUPAL_VERSION="^8.5@alpha" DB_TYPE="mysql" DB_HOST="localhost"
  - env: LANGCODE="en" PROFILE="standard" DRUPAL_VERSION="^8.5@alpha" DB_TYPE="sqlite"
  - env: LANGCODE="en" PROFILE="standard" DRUPAL_VERSION="^8.5@alpha" DB_TYPE="pgsql" DB_HOST="/var/run/postgresql" DB_PORT=5432
  - env: LANGCODE="fr" PROFILE="standard" DRUPAL_VERSION="^8.5@alpha" DB_TYPE="mysql" DB_HOST="localhost"
  - env: LANGCODE="fr" PROFILE="standard" DRUPAL_VERSION="^8.5@alpha" DB_TYPE="sqlite"
  - env: LANGCODE="fr" PROFILE="standard" DRUPAL_VERSION="^8.5@alpha" DB_TYPE="pgsql" DB_HOST="/var/run/postgresql" DB_PORT=5432

before_install:
- echo $T
- install --directory .travis/bin
# - if [[ -f config/parameters.yml.travis ]]; then cp config/parameters.yml.travis config/parameters.yml; fi
- wget http://get.sensiolabs.org/security-checker.phar --output-document=.travis/bin/security-checker

# - pip install pygments # but now pygmentize is no more used right here.
- go get -u github.com/jingweno/ccat

install:
- composer create-project --no-install --stability dev --no-interaction drupal-composer/drupal-project my-project $SKELETON_VERSION
- cd my-project
- if [[ -v DRUPAL_VERSION ]]; then composer -vv require --no-update drupal/core:$DRUPAL_VERSION; fi
- composer install

before_script:
- composer show
# - bin/console
- ls --color
- ls drush
- ls --color vendor/bin
- $GOPATH/bin/ccat composer.json
- find . -name profiles
- cd web
- ls --color
- ls --color profiles
- ../vendor/bin/drupal
- ../vendor/bin/drupal help init # Copy configuration files.
- ../vendor/bin/drupal help chain --file=~/.console/chain/quick-start.yml # Used to eg. download, install and serve.
- ../vendor/bin/drupal help quick:start # Maybe shortcut for chain --file=~/.console/chain/quick-start.yml
- ../vendor/bin/drupal help site:new # Looks like download.
- ../vendor/bin/drupal help site:install # Maybe installation: basic configuration
- ../vendor/bin/drupal help server
- ../vendor/bin/drush 2> /dev/null # drush/drush 8.1.15 does not fold and has lots of warnings (may be with too recent php version).
# - ls -R --color bin config public src
# - ls -R --color var
# - ../vendor/bin/drupal init --yes --destination=~/.console/ --no-interaction
# - ../vendor/bin/drupal quick:start --yes --no-interaction
- mysql -e 'CREATE DATABASE IF NOT EXISTS travis_ci_test;'
- psql --command="create database $USER;" -U postgres # --encoding=UTF8 --owner=username
- psql --command="\l" -U postgres
- ../vendor/bin/drupal site:install $PROFILE --yes --no-interaction --verbose
  --langcode=$LANGCODE
  --db-type=$DB_TYPE
  --db-host=$DB_HOST
  --db-port=$DB_PORT
  --db-name=$USER
  --db-user=$USER
  --db-pass=""
  --site-name="Project Only"
  --site-mail="admin@example.com"
  --account-name="admin"
  --account-mail="admin@example.com"
  --account-pass="admin"

- ../vendor/bin/drush core-status
- ../vendor/bin/drush core-requirements
- ../vendor/bin/drupal server --yes --no-interaction --learning &
- printf 'HEAD / HTTP/1.1\r\n\r\n' | socat - TCP4:localhost:8088,forever # Waiting for server to connect.

script:
- elinks http://localhost:8088/ -dump-color-mode 4 -dump
- elinks http://localhost:8088/core/install.php?langcode=en -dump-color-mode 4 -dump

- cd ..
- php ../.travis/bin/security-checker --version
- php ../.travis/bin/security-checker security:check --end-point=http://security.sensiolabs.org/check_lock
- 'curl -H "Accept: text/plain" https://security.sensiolabs.org/check_lock -F lock=@composer.lock'
  #^ This checks that the application doesn't use dependencies with known security vulnerabilities
